services:
  - type: web
    name: sistema-notas-java
    runtime: docker
    repo: https://github.com/Deimer1991/ProyectoIntegradorBackend
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://db.prisma.io:5432/postgres?sslmode=require
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        value: clave-super-secreta-sistema-de-notas-2026-debe-ser-larga
      - key: APP_JWT_EXPIRATION
        value: "86400000"
      - key: APP_FRONTEND_URL
        value: https://proyectointegradorfrontend.onrender.com
      - key: SPRING_MAIL_USERNAME
        value: deimer.yav@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: ssad kuhd zjud nnrn
