spring.application.name=sistemadenotas

spring.config.import=optional:file:.env[.properties]

# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Cambia el nivel global a solo Advertencias y Errores

server.port=8081

# Correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=deimer.yav@gmail.com
spring.mail.password=ssad kuhd zjud nnrn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL del frontend (para armar el link del correo)
app.frontend.url=http://localhost:5173

app.jwt.secret=clave-super-secreta-sistema-de-notas-2026-debe-ser-larga
app.jwt.expiration=86400000